Vagrant.configure("2") do |config|   
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "vagrant-{{ box_name }}"

    config.vm.provider "virtualbox" do |v|
        v.name = "vagrant-{{ box_name }}"
        v.memory = {{ box_memory }}
        v.cpus = {{ box_cpu }}
    end

    config.vm.provision :ansible do |ansible|
        ansible.verbose = false
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "playbook.yml"
        ansible.galaxy_role_file = "requirements.yml"
        ansible.galaxy_roles_path = "/etc/ansible/roles"
        ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
    end

    config.trigger.before :destroy do |trigger|
        trigger.run_remote = {inline: "tailscale logout"}
        trigger.on_error = :continue
    end
end
